version: '3'
services:
  digdag_embulk:
    container_name: digdag_embulk
    build: docker/digdag_embulk
    tty: true
    working_dir: "/var/data"
    volumes:
      - .:/var/data

  db:
    container_name: db
    build: docker/postgresql
    tty: true
    ports:
      - 5433:5432